version: "3.8"

services:
  db:
    image: postgres
    container_name: db-viacep
    restart: always
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 1024M

    environment:
      POSTGRES_PASSWORD: "1234"
    volumes:
      - "./src/main/resources/sql/:/docker-entrypoint-initdb.d"